name:                InterleavedBinaries
version:             0.0.1
github:              "mishajw/InterleavedBinaries"
license:             BSD3
author:              "Misha Wagner"
maintainer:          "mishajw@gmail.com"
copyright:           "2018 Misha Wagner"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mishajw/InterleavedBinaries#readme>

dependencies:
- base >= 4.7 && < 5
- process
- temporary
- filepath
- split
- mtl
- text
- regex-compat

library:
  source-dirs: src

executables:
  InterleavedBinaries-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - InterleavedBinaries

tests:
  InterleavedBinaries-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - InterleavedBinaries

